### ISSUE TITLE
pytest --boxed test in windows assert  'ForkedFunc' object has no attribute 'pid'

### ISSUE THREAD

**Issue by nooperpudd** [pytest-dev/pytest-forked#6]
```
INTERNALERROR>   File "c:\python35-x64\lib\site-packages\pytest_forked\__init__.py", line 35, in pytest_runtest_protocol
INTERNALERROR>     reports = forked_run_report(item)
INTERNALERROR>   File "c:\python35-x64\lib\site-packages\pytest_forked\__init__.py", line 55, in forked_run_report
INTERNALERROR>     ff = py.process.ForkedFunc(runforked)
INTERNALERROR>   File "c:\python35-x64\lib\site-packages\py\_process\forkedfunc.py", line 45, in __init__
INTERNALERROR>     pid = os.fork()
INTERNALERROR> AttributeError: module 'os' has no attribute 'fork'
======================== no tests ran in 0.17 seconds =========================
Exception ignored in: <bound method ForkedFunc.__del__ of <py._process.forkedfunc.ForkedFunc object at 0x000000E9B647F898>>
Traceback (most recent call last):
  File "c:\python35-x64\lib\site-packages\py\_process\forkedfunc.py", line 110, in __del__
    if self.pid is not None:  # only clean up in main process
AttributeError: 'ForkedFunc' object has no attribute 'pid'
```
details:
https://ci.appveyor.com/project/nooperpudd/quantbube/build/1.0.38/job/7pdjtq6p78hu2127

**Comment by RonnyPfannschmidt** [comment]
windows has no fork support
